{% set name = "tree-math" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tree-math-{{ version }}.tar.gz
  sha256: 77613c2360e067b16c0738b32e7d64aa5e1167e609ca1a32b6fa05dcb0d330bb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.0
  run:
    - jax
    - python >=3.0

test:
  imports:
    - tree_math
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/tree-math
  summary: Mathematical operations for JAX pytrees
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - ngam
