{% set name = "tree-math" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tree-math-{{ version }}.tar.gz
  sha256: fced2b436fa265b4e24ab46b5768d7b03a4a8d0b75de8a5ab110abaeac3b5772

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.0
  run:
    - jax
    - python >=3.0

test:
  imports:
    - tree_math
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/tree-math
  summary: Mathematical operations for JAX pytrees
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - ngam
